### ISSUE TITLE
About creating an inode at master 301

### ISSUE THREAD

**Issue by maojr** [thejinxters/simple_linux_character_driver#1]
Hi,I am a  linux driver newbie and I tried your linux driver code.

I found error when I  follow your ReadMe.md.

Create an inode at master 301 with 

``` bash
sudo mknod -m 777 /dev/simple_char_device 777 c 301 0
```

but when I remove the last 777,it worked.

``` bash
sudo mknod -m 777 /dev/simple_char_device  c 301 0
```

So I think that there maybe some mistakes.

By the way,thank you for you sharing.

**Comment by thejinxters** [comment]
thanks! that definitely looks like a typo. Cheers!

**Comment by maojr** [comment]
Cheers.

Will you fix it?

2015-07-09 1:38 GMT+00:00 Brandon Mikulka notifications@github.com:
